sprite_names = ['???', 'Finish line arch',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                'Goforit 1 (Gopher)',
                'Goforit 2 (Gopher)',
                'Albert (Bird)',
                '???',
                '???',
                'Putt (Bird)',
                '???',
                'Fineous (Shark fin)',
                'Fizzie (Fish)',
                'Fizzie 2 (Fish)',
                'Comet',
                'Hanging Harry',
                'McMoose',
                'Fitch (Flower)',
                'Floating Leaf',
                'Leaf spawner',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                'Splinter (Beaver)',
                '???',
                '???',
                'Frogo (Frozen guy)',
                'Dee-Thaw (Snowman)',
                'Shno-zer (Snowman)',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                'Gerg (Crab)',
                '???',
                'Pokums (Drill)',
                '???',
                'Propbot (Flying bot)',
                'Draggie (Snail)',
                'Nerb L (Fire)',
                'Nerb R (Fire)',
                'Dwayne (Rock)',
                '???',
                '???',
                'Whirlee (Robot)',
                'Zipper 1',
                'Zipper 2',
                '???',
                '???',
                'Path spring',
                '???',
                '???',
                '???',
                '???',
                'Boss',
                'Moon  tongue',
                '???',
                'Krome-Dome (Caveman)',
                'Leinad (Caveman)',
                '???',
                '???',
                'Fill-in-block',
                'Fill-in-space',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                '???',
                'Cloud 1',
                'Cloud 2',
                'Cloud 3',
                'Conveyor',
                'Boat',
                '???',
                'Platform 1',
                'Platform 2',
                'Clow-platform',
                'Big spring',
                'Big spring U',
                '???',
                '???',
                '???',
                '???',
                '???',
                'Zipper 3',
                'Zipper 4',
                'Zipper 5',
                'Zipper 6',
                'Zipper 7',
                'Zipper 8',
                'Zipper 9',
                'Zipper 10',
                'Zipper 11',
                'Zipper 12',
                'Zipper 13',
                'Zipper 14',
                'Zipper 15',
                'Zipper 16',
                'Zipper 17',
                'Zipper 18',
                'Zipper 19',
                'Zipper 20',
                'Zipper 21',
                'Zipper 22',
                'Zipper 23',
                'Zipper 24',
                'Zipper 25',
                'Zipper 26',
                '???'
                ]
